function OmegaCoeffs = SymOmegaCoefficients(coeffs,i,j)
    % So much algebra...
    OmegaCoeffs = [
         (cross(coeffs.G11(:,i),coeffs.G11(:,j))'*coeffs.H11);
         (cross(coeffs.G11(:,i),coeffs.G11(:,j))'*coeffs.H12 + ...
              cross(coeffs.G11(:,i),coeffs.G12(:,j))'*coeffs.H11 + ...
              cross(coeffs.G12(:,i),coeffs.G11(:,j))'*coeffs.H11);
         (cross(coeffs.G11(:,i),coeffs.G11(:,j))'*coeffs.H13 + ...
              cross(coeffs.G11(:,i),coeffs.G13(:,j))'*coeffs.H11 + ...
              cross(coeffs.G13(:,i),coeffs.G11(:,j))'*coeffs.H11);
         (cross(coeffs.G11(:,i),coeffs.G11(:,j))'*coeffs.H22 + ...
              cross(coeffs.G11(:,i),coeffs.G12(:,j))'*coeffs.H12 + ...
              cross(coeffs.G12(:,i),coeffs.G11(:,j))'*coeffs.H12 + ...
              cross(coeffs.G11(:,i),coeffs.G22(:,j))'*coeffs.H11 + ...
              cross(coeffs.G12(:,i),coeffs.G12(:,j))'*coeffs.H11 + ...
              cross(coeffs.G22(:,i),coeffs.G11(:,j))'*coeffs.H11);
         (cross(coeffs.G11(:,i),coeffs.G11(:,j))'*coeffs.H23 + ...
              cross(coeffs.G11(:,i),coeffs.G13(:,j))'*coeffs.H12 + ...
              cross(coeffs.G13(:,i),coeffs.G11(:,j))'*coeffs.H12 + ...
              cross(coeffs.G11(:,i),coeffs.G12(:,j))'*coeffs.H13 + ...
              cross(coeffs.G12(:,i),coeffs.G11(:,j))'*coeffs.H13 + ...
              cross(coeffs.G11(:,i),coeffs.G23(:,j))'*coeffs.H11 + ...
              cross(coeffs.G12(:,i),coeffs.G13(:,j))'*coeffs.H11 + ...
              cross(coeffs.G13(:,i),coeffs.G12(:,j))'*coeffs.H11 + ...
              cross(coeffs.G23(:,i),coeffs.G11(:,j))'*coeffs.H11);
         (cross(coeffs.G11(:,i),coeffs.G11(:,j))'*coeffs.H33 + ...
              cross(coeffs.G11(:,i),coeffs.G13(:,j))'*coeffs.H13 + ...
              cross(coeffs.G13(:,i),coeffs.G11(:,j))'*coeffs.H13 + ...
              cross(coeffs.G11(:,i),coeffs.G33(:,j))'*coeffs.H11 + ...
              cross(coeffs.G13(:,i),coeffs.G13(:,j))'*coeffs.H11 + ...
              cross(coeffs.G33(:,i),coeffs.G11(:,j))'*coeffs.H11);
         (cross(coeffs.G11(:,i),coeffs.G12(:,j))'*coeffs.H22 + ...
              cross(coeffs.G12(:,i),coeffs.G11(:,j))'*coeffs.H22 + ...
              cross(coeffs.G11(:,i),coeffs.G22(:,j))'*coeffs.H12 + ...
              cross(coeffs.G12(:,i),coeffs.G12(:,j))'*coeffs.H12 + ...
              cross(coeffs.G22(:,i),coeffs.G11(:,j))'*coeffs.H12 + ...
              cross(coeffs.G12(:,i),coeffs.G22(:,j))'*coeffs.H11 + ...
              cross(coeffs.G22(:,i),coeffs.G12(:,j))'*coeffs.H11);
         (cross(coeffs.G11(:,i),coeffs.G12(:,j))'*coeffs.H23 + ...
              cross(coeffs.G12(:,i),coeffs.G11(:,j))'*coeffs.H23 + ...
              cross(coeffs.G11(:,i),coeffs.G13(:,j))'*coeffs.H22 + ...
              cross(coeffs.G13(:,i),coeffs.G11(:,j))'*coeffs.H22 + ...
              cross(coeffs.G11(:,i),coeffs.G22(:,j))'*coeffs.H13 + ...
              cross(coeffs.G12(:,i),coeffs.G12(:,j))'*coeffs.H13 + ...
              cross(coeffs.G22(:,i),coeffs.G11(:,j))'*coeffs.H13 + ...
              cross(coeffs.G11(:,i),coeffs.G23(:,j))'*coeffs.H12 + ...
              cross(coeffs.G12(:,i),coeffs.G13(:,j))'*coeffs.H12 + ...
              cross(coeffs.G13(:,i),coeffs.G12(:,j))'*coeffs.H12 + ...
              cross(coeffs.G23(:,i),coeffs.G11(:,j))'*coeffs.H12 + ...
              cross(coeffs.G12(:,i),coeffs.G23(:,j))'*coeffs.H11 + ...
              cross(coeffs.G13(:,i),coeffs.G22(:,j))'*coeffs.H11 + ...
              cross(coeffs.G22(:,i),coeffs.G13(:,j))'*coeffs.H11 + ...
              cross(coeffs.G23(:,i),coeffs.G12(:,j))'*coeffs.H11);
         (cross(coeffs.G11(:,i),coeffs.G12(:,j))'*coeffs.H33 + ...
              cross(coeffs.G12(:,i),coeffs.G11(:,j))'*coeffs.H33 + ...
              cross(coeffs.G11(:,i),coeffs.G13(:,j))'*coeffs.H23 + ...
              cross(coeffs.G13(:,i),coeffs.G11(:,j))'*coeffs.H23 + ...
              cross(coeffs.G11(:,i),coeffs.G23(:,j))'*coeffs.H13 + ...
              cross(coeffs.G12(:,i),coeffs.G13(:,j))'*coeffs.H13 + ...
              cross(coeffs.G13(:,i),coeffs.G12(:,j))'*coeffs.H13 + ...
              cross(coeffs.G23(:,i),coeffs.G11(:,j))'*coeffs.H13 + ...
              cross(coeffs.G11(:,i),coeffs.G33(:,j))'*coeffs.H12 + ...
              cross(coeffs.G13(:,i),coeffs.G13(:,j))'*coeffs.H12 + ...
              cross(coeffs.G33(:,i),coeffs.G11(:,j))'*coeffs.H12 + ...
              cross(coeffs.G12(:,i),coeffs.G33(:,j))'*coeffs.H11 + ...
              cross(coeffs.G13(:,i),coeffs.G23(:,j))'*coeffs.H11 + ...
              cross(coeffs.G23(:,i),coeffs.G13(:,j))'*coeffs.H11 + ...
              cross(coeffs.G33(:,i),coeffs.G12(:,j))'*coeffs.H11 + ...
              0);
         (cross(coeffs.G11(:,i),coeffs.G13(:,j))'*coeffs.H33 + ...
              cross(coeffs.G13(:,i),coeffs.G11(:,j))'*coeffs.H33 + ...
              cross(coeffs.G11(:,i),coeffs.G33(:,j))'*coeffs.H13 + ...
              cross(coeffs.G13(:,i),coeffs.G13(:,j))'*coeffs.H13 + ...
              cross(coeffs.G33(:,i),coeffs.G11(:,j))'*coeffs.H13 + ...
              cross(coeffs.G13(:,i),coeffs.G33(:,j))'*coeffs.H11 + ...
              cross(coeffs.G33(:,i),coeffs.G13(:,j))'*coeffs.H11 + ...
              0);
         (cross(coeffs.G11(:,i),coeffs.G22(:,j))'*coeffs.H22 + ...
              cross(coeffs.G12(:,i),coeffs.G12(:,j))'*coeffs.H22 + ...
              cross(coeffs.G22(:,i),coeffs.G11(:,j))'*coeffs.H22 + ...
              cross(coeffs.G22(:,i),coeffs.G12(:,j))'*coeffs.H12 + ...
              cross(coeffs.G12(:,i),coeffs.G22(:,j))'*coeffs.H12 + ...
              cross(coeffs.G22(:,i),coeffs.G22(:,j))'*coeffs.H11);
         (cross(coeffs.G11(:,i),coeffs.G22(:,j))'*coeffs.H23 + ...
              cross(coeffs.G12(:,i),coeffs.G12(:,j))'*coeffs.H23 + ...
              cross(coeffs.G22(:,i),coeffs.G11(:,j))'*coeffs.H23 + ...
              cross(coeffs.G11(:,i),coeffs.G23(:,j))'*coeffs.H22 + ...
              cross(coeffs.G12(:,i),coeffs.G13(:,j))'*coeffs.H22 + ...
              cross(coeffs.G13(:,i),coeffs.G12(:,j))'*coeffs.H22 + ...
              cross(coeffs.G23(:,i),coeffs.G11(:,j))'*coeffs.H22 + ...
              cross(coeffs.G12(:,i),coeffs.G22(:,j))'*coeffs.H13 + ...
              cross(coeffs.G22(:,i),coeffs.G12(:,j))'*coeffs.H13 + ...
              cross(coeffs.G12(:,i),coeffs.G23(:,j))'*coeffs.H12 + ...
              cross(coeffs.G13(:,i),coeffs.G22(:,j))'*coeffs.H12 + ...
              cross(coeffs.G22(:,i),coeffs.G13(:,j))'*coeffs.H12 + ...
              cross(coeffs.G23(:,i),coeffs.G12(:,j))'*coeffs.H12 + ...
              cross(coeffs.G22(:,i),coeffs.G23(:,j))'*coeffs.H11 + ...
              cross(coeffs.G23(:,i),coeffs.G22(:,j))'*coeffs.H11);
         (cross(coeffs.G11(:,i),coeffs.G22(:,j))'*coeffs.H33 + ...
              cross(coeffs.G12(:,i),coeffs.G12(:,j))'*coeffs.H33 + ...
              cross(coeffs.G22(:,i),coeffs.G11(:,j))'*coeffs.H33 + ...
              cross(coeffs.G11(:,i),coeffs.G23(:,j))'*coeffs.H23 + ...
              cross(coeffs.G12(:,i),coeffs.G13(:,j))'*coeffs.H23 + ...
              cross(coeffs.G13(:,i),coeffs.G12(:,j))'*coeffs.H23 + ...
              cross(coeffs.G23(:,i),coeffs.G11(:,j))'*coeffs.H23 + ...
              cross(coeffs.G11(:,i),coeffs.G33(:,j))'*coeffs.H22 + ...
              cross(coeffs.G13(:,i),coeffs.G13(:,j))'*coeffs.H22 + ...
              cross(coeffs.G33(:,i),coeffs.G11(:,j))'*coeffs.H22 + ...
              cross(coeffs.G12(:,i),coeffs.G23(:,j))'*coeffs.H13 + ...
              cross(coeffs.G13(:,i),coeffs.G22(:,j))'*coeffs.H13 + ...
              cross(coeffs.G22(:,i),coeffs.G13(:,j))'*coeffs.H13 + ...
              cross(coeffs.G23(:,i),coeffs.G12(:,j))'*coeffs.H13 + ...
              cross(coeffs.G12(:,i),coeffs.G33(:,j))'*coeffs.H12 + ...
              cross(coeffs.G13(:,i),coeffs.G23(:,j))'*coeffs.H12 + ...
              cross(coeffs.G23(:,i),coeffs.G13(:,j))'*coeffs.H12 + ...
              cross(coeffs.G33(:,i),coeffs.G12(:,j))'*coeffs.H12 + ...
              cross(coeffs.G22(:,i),coeffs.G33(:,j))'*coeffs.H11 + ...
              cross(coeffs.G23(:,i),coeffs.G23(:,j))'*coeffs.H11 + ...
              cross(coeffs.G33(:,i),coeffs.G22(:,j))'*coeffs.H11);
         (cross(coeffs.G11(:,i),coeffs.G23(:,j))'*coeffs.H33 + ...
              cross(coeffs.G12(:,i),coeffs.G13(:,j))'*coeffs.H33 + ...
              cross(coeffs.G13(:,i),coeffs.G12(:,j))'*coeffs.H33 + ...
              cross(coeffs.G23(:,i),coeffs.G11(:,j))'*coeffs.H33 + ...
              cross(coeffs.G11(:,i),coeffs.G33(:,j))'*coeffs.H23 + ...
              cross(coeffs.G13(:,i),coeffs.G13(:,j))'*coeffs.H23 + ...
              cross(coeffs.G33(:,i),coeffs.G11(:,j))'*coeffs.H23 + ...
              cross(coeffs.G12(:,i),coeffs.G33(:,j))'*coeffs.H13 + ...
              cross(coeffs.G13(:,i),coeffs.G23(:,j))'*coeffs.H13 + ...
              cross(coeffs.G23(:,i),coeffs.G13(:,j))'*coeffs.H13 + ...
              cross(coeffs.G33(:,i),coeffs.G12(:,j))'*coeffs.H13 + ...
              cross(coeffs.G13(:,i),coeffs.G33(:,j))'*coeffs.H12 + ...
              cross(coeffs.G33(:,i),coeffs.G13(:,j))'*coeffs.H12 + ...
              cross(coeffs.G23(:,i),coeffs.G33(:,j))'*coeffs.H11 + ...
              cross(coeffs.G33(:,i),coeffs.G23(:,j))'*coeffs.H11);
         (cross(coeffs.G11(:,i),coeffs.G33(:,j))'*coeffs.H33 + ...
              cross(coeffs.G13(:,i),coeffs.G13(:,j))'*coeffs.H33 + ...
              cross(coeffs.G33(:,i),coeffs.G11(:,j))'*coeffs.H33 + ...
              cross(coeffs.G13(:,i),coeffs.G33(:,j))'*coeffs.H13 + ...
              cross(coeffs.G33(:,i),coeffs.G13(:,j))'*coeffs.H13 + ...
              cross(coeffs.G33(:,i),coeffs.G33(:,j))'*coeffs.H11 + ...
              0);
         (cross(coeffs.G12(:,i),coeffs.G22(:,j))'*coeffs.H22 + ...
              cross(coeffs.G22(:,i),coeffs.G12(:,j))'*coeffs.H22 + ...
              cross(coeffs.G22(:,i),coeffs.G22(:,j))'*coeffs.H12 + ...
              0);
         (cross(coeffs.G12(:,i),coeffs.G22(:,j))'*coeffs.H23 + ...
              cross(coeffs.G22(:,i),coeffs.G12(:,j))'*coeffs.H23 + ...
              cross(coeffs.G12(:,i),coeffs.G23(:,j))'*coeffs.H22 + ...
              cross(coeffs.G13(:,i),coeffs.G22(:,j))'*coeffs.H22 + ...
              cross(coeffs.G22(:,i),coeffs.G13(:,j))'*coeffs.H22 + ...
              cross(coeffs.G23(:,i),coeffs.G12(:,j))'*coeffs.H22 + ...
              cross(coeffs.G22(:,i),coeffs.G22(:,j))'*coeffs.H13 + ...
              cross(coeffs.G22(:,i),coeffs.G23(:,j))'*coeffs.H12 + ...
              cross(coeffs.G23(:,i),coeffs.G22(:,j))'*coeffs.H12 + ...
              0);
         (cross(coeffs.G12(:,i),coeffs.G22(:,j))'*coeffs.H33 + ...
              cross(coeffs.G22(:,i),coeffs.G12(:,j))'*coeffs.H33 + ...
              cross(coeffs.G12(:,i),coeffs.G23(:,j))'*coeffs.H23 + ...
              cross(coeffs.G13(:,i),coeffs.G22(:,j))'*coeffs.H23 + ...
              cross(coeffs.G22(:,i),coeffs.G13(:,j))'*coeffs.H23 + ...
              cross(coeffs.G23(:,i),coeffs.G12(:,j))'*coeffs.H23 + ...
              cross(coeffs.G12(:,i),coeffs.G33(:,j))'*coeffs.H22 + ...
              cross(coeffs.G13(:,i),coeffs.G23(:,j))'*coeffs.H22 + ...
              cross(coeffs.G23(:,i),coeffs.G13(:,j))'*coeffs.H22 + ...
              cross(coeffs.G33(:,i),coeffs.G12(:,j))'*coeffs.H22 + ...
              cross(coeffs.G22(:,i),coeffs.G23(:,j))'*coeffs.H13 + ...
              cross(coeffs.G23(:,i),coeffs.G22(:,j))'*coeffs.H13 + ...
              cross(coeffs.G22(:,i),coeffs.G33(:,j))'*coeffs.H12 + ...
              cross(coeffs.G23(:,i),coeffs.G23(:,j))'*coeffs.H12 + ...
              cross(coeffs.G33(:,i),coeffs.G22(:,j))'*coeffs.H12 + ...
              0);
         (cross(coeffs.G12(:,i),coeffs.G23(:,j))'*coeffs.H33 + ...
              cross(coeffs.G13(:,i),coeffs.G22(:,j))'*coeffs.H33 + ...
              cross(coeffs.G22(:,i),coeffs.G13(:,j))'*coeffs.H33 + ...
              cross(coeffs.G23(:,i),coeffs.G12(:,j))'*coeffs.H33 + ...
              cross(coeffs.G12(:,i),coeffs.G33(:,j))'*coeffs.H23 + ...
              cross(coeffs.G13(:,i),coeffs.G23(:,j))'*coeffs.H23 + ...
              cross(coeffs.G23(:,i),coeffs.G13(:,j))'*coeffs.H23 + ...
              cross(coeffs.G33(:,i),coeffs.G12(:,j))'*coeffs.H23 + ...
              cross(coeffs.G13(:,i),coeffs.G33(:,j))'*coeffs.H22 + ...
              cross(coeffs.G33(:,i),coeffs.G13(:,j))'*coeffs.H22 + ...
              cross(coeffs.G22(:,i),coeffs.G33(:,j))'*coeffs.H13 + ...
              cross(coeffs.G23(:,i),coeffs.G23(:,j))'*coeffs.H13 + ...
              cross(coeffs.G33(:,i),coeffs.G22(:,j))'*coeffs.H13 + ...
              cross(coeffs.G23(:,i),coeffs.G33(:,j))'*coeffs.H12 + ...
              cross(coeffs.G33(:,i),coeffs.G23(:,j))'*coeffs.H12 + ...
              0);
         (cross(coeffs.G12(:,i),coeffs.G33(:,j))'*coeffs.H33 + ...
              cross(coeffs.G13(:,i),coeffs.G23(:,j))'*coeffs.H33 + ...
              cross(coeffs.G23(:,i),coeffs.G13(:,j))'*coeffs.H33 + ...
              cross(coeffs.G33(:,i),coeffs.G12(:,j))'*coeffs.H33 + ...
              cross(coeffs.G13(:,i),coeffs.G33(:,j))'*coeffs.H23 + ...
              cross(coeffs.G33(:,i),coeffs.G13(:,j))'*coeffs.H23 + ...
              cross(coeffs.G23(:,i),coeffs.G33(:,j))'*coeffs.H13 + ...
              cross(coeffs.G33(:,i),coeffs.G23(:,j))'*coeffs.H13 + ...
              cross(coeffs.G33(:,i),coeffs.G33(:,j))'*coeffs.H12 + ...
              0);
         (cross(coeffs.G13(:,i),coeffs.G33(:,j))'*coeffs.H33 + ...
              cross(coeffs.G33(:,i),coeffs.G13(:,j))'*coeffs.H33 + ...
              cross(coeffs.G33(:,i),coeffs.G33(:,j))'*coeffs.H13 + ...
              0);
         (cross(coeffs.G22(:,i),coeffs.G22(:,j))'*coeffs.H22);
         (cross(coeffs.G22(:,i),coeffs.G22(:,j))'*coeffs.H23 + ...
              cross(coeffs.G22(:,i),coeffs.G23(:,j))'*coeffs.H22 + ...
              cross(coeffs.G23(:,i),coeffs.G22(:,j))'*coeffs.H22);
         (cross(coeffs.G22(:,i),coeffs.G22(:,j))'*coeffs.H33 + ...
              cross(coeffs.G22(:,i),coeffs.G23(:,j))'*coeffs.H23 + ...
              cross(coeffs.G23(:,i),coeffs.G22(:,j))'*coeffs.H23 + ...
              cross(coeffs.G22(:,i),coeffs.G33(:,j))'*coeffs.H22 + ...
              cross(coeffs.G23(:,i),coeffs.G23(:,j))'*coeffs.H22 + ...
              cross(coeffs.G33(:,i),coeffs.G22(:,j))'*coeffs.H22);
         (cross(coeffs.G22(:,i),coeffs.G23(:,j))'*coeffs.H33 + ...
              cross(coeffs.G23(:,i),coeffs.G22(:,j))'*coeffs.H33 + ...
              cross(coeffs.G22(:,i),coeffs.G33(:,j))'*coeffs.H23 + ...
              cross(coeffs.G23(:,i),coeffs.G23(:,j))'*coeffs.H23 + ...
              cross(coeffs.G33(:,i),coeffs.G22(:,j))'*coeffs.H23 + ...
              cross(coeffs.G23(:,i),coeffs.G33(:,j))'*coeffs.H22 + ...
              cross(coeffs.G33(:,i),coeffs.G23(:,j))'*coeffs.H22 + ...
              0);
         (cross(coeffs.G22(:,i),coeffs.G33(:,j))'*coeffs.H33 + ...
              cross(coeffs.G23(:,i),coeffs.G23(:,j))'*coeffs.H33 + ...
              cross(coeffs.G33(:,i),coeffs.G22(:,j))'*coeffs.H33 + ...
              cross(coeffs.G23(:,i),coeffs.G33(:,j))'*coeffs.H23 + ...
              cross(coeffs.G33(:,i),coeffs.G23(:,j))'*coeffs.H23 + ...
              cross(coeffs.G33(:,i),coeffs.G33(:,j))'*coeffs.H22 + ...
              0);
         (cross(coeffs.G23(:,i),coeffs.G33(:,j))'*coeffs.H33 + ...
              cross(coeffs.G33(:,i),coeffs.G23(:,j))'*coeffs.H33 + ...
              cross(coeffs.G33(:,i),coeffs.G33(:,j))'*coeffs.H23 + ...
              0);
         (cross(coeffs.G33(:,i),coeffs.G33(:,j))'*coeffs.H33) ];
end

